### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by ochremiak** [szymtor/locfin#10]
Hej!

Przeczytałam intro. Mam takie uwagi:  (trochę się rozpisałam - ciekawe, czy przebrniecie ;)

- przy redukcji CFI do IBCC nadal jest k=2 (ale może tylko w mojej aktualnej lokalnej wersji ;)
- Przykład templatu orbit-finite z kolorowaniem grafów atomami (Example 3). W dalszej części intro jest podany template skończony, który mu odpowiada. Rozumiem, że on jest taki (relacje bez jednej pary), bo tak jest łatwiej go opisać, ale trochę się obawiam, że dla czytelników bez doświadczenia z CSP, to może być niejasne tzn. skąd on się bierze i dlaczego te relacje wystarczą do wyrażenia oryginalnego problemu. Niestety nie mam pomysłu jak to rozjaśnić

- We show that an instance of IBCC naturally defines a CSP instance over a locally finite template:
1) Moim zdaniem dla ludzi myślących "normalnie" ta konstrukcja nie opisuje templatu lokalnie-skończonego, ale skończony: wartościamy są bijekcje pomiędzy skończonymi grafami, takich bijekcji jest skończenie wiele itd. Dopiero komentarz poniżej opisuje jak można w tym zobaczyć template orbitowo-skończony.
2) Ponadto, skoro czytelnik w naturalny sposób widzi IBCC jako instancję nad skończonym templatem, to myśli sobie: "OK, skończony template wystarczy" i ten przykład nie dowodzi użyteczności naszych templatów. Z tego co ja rozumiem (nie wiem, czy poprawnie) IBCC nie można zdefiniować jako instancji nad skończonym templatem przy pomocy LFP i dlatego ten skończony template nie jest ok i potrzebujemy nieskończonego? I to jest niby zasugerowane wcześniej... Ale nie wiem, czy to nie jest ciut zbyt zbyt skomplikowane.

Pozdrawiam,
Asia

**Comment by szymtor** [comment]
>
>
>    - przy redukcji CFI do IBCC nadal jest k=2 (ale może tylko w mojej
>    aktualnej lokalnej wersji ;)
>
> Tak, ktoś to musi jeszcze wprowadzić. Pozostawiam intro Bartkowi.

>
>    -
>
>    Przykład templatu orbit-finite z kolorowaniem grafów atomami (Example
>    3). W dalszej części intro jest podany template skończony, który mu
>    odpowiada. Rozumiem, że on jest taki (relacje bez jednej pary), bo tak jest
>    łatwiej go opisać, ale trochę się obawiam, że dla czytelników bez
>    doświadczenia z CSP, to może być niejasne tzn. skąd on się bierze i
>    dlaczego te relacje wystarczą do wyrażenia oryginalnego problemu. Niestety
>    nie mam pomysłu jak to rozjaśnić
>
> Myślę, że tu można rozjaśnić opisując, jak przerobić instancję nad starym
templatem na nową instancję.

>
>    -
>
>    We show that an instance of IBCC naturally defines a CSP instance over
>    a locally finite template:
>    1) Moim zdaniem dla ludzi myślących "normalnie" ta konstrukcja nie
>    opisuje templatu lokalnie-skończonego, ale skończony: wartościamy są
>    bijekcje pomiędzy skończonymi grafami, takich bijekcji jest skończenie
>    wiele itd. Dopiero komentarz poniżej opisuje jak można w tym zobaczyć
>    template orbitowo-skończony.
>
> Rozumiem, że chodzi Ci o template skończony, składający się dokładnie z
tych relacji, które pojawiają się w ustalonej (skończonej) instancji?
Tak, owszem, jest. (Tu pojawia się jeden problem formalny – wg definicji,
instancja powinna mieć określony zbiór dopuszczalnych wartości [domain] – a
tu tego nie określamy. A gdybyśmy go określili, to by wyszła instancja
właśnie nad tym templatem skończony, a nie tym nieskończonym).

>
>    -
>
>    2) Ponadto, skoro czytelnik w naturalny sposób widzi IBCC jako
>    instancję nad skończonym templatem, to myśli sobie: "OK, skończony template
>    wystarczy" i ten przykład nie dowodzi użyteczności naszych templatów. Z
>    tego co ja rozumiem (nie wiem, czy poprawnie) IBCC nie można zdefiniować
>    jako instancji nad skończonym templatem przy pomocy LFP i dlatego ten
>    skończony template nie jest ok i potrzebujemy nieskończonego?I to jest niby
>    zasugerowane wcześniej... Ale nie wiem, czy to nie jest ciut zbyt zbyt
>    skomplikowane.
>
> To prawda, to dla mnie to jest mega skomplikowane i niejasne. Po co nam
template nieskończony, skoro możemy mieć ten skończony? LFP nie robi
różnicy, czy produkuje instancję nad jednym czy drugim templatem, bo te
instancje wyglądają identycznie. Dodatkowo, jakby LFP miało sprecyzować
dziedzinę tej instancji, to by prędzej potrafiło opisać tę dziedzinę
skończoną niż tę nieskończoną. Więc faktycznie LFP definuje tę instancję
nad skończonym templatem...

Ale jeżeli my chcemy zbadać (już nie używając LFP, tylko zewnętrznie), czy
wszystkie te templaty mają Malcewa, czy nie, to używamy jednego
nieskończonego templata. Bardzo szemrana ta motywacja...

**Comment by ochremiak** [comment]
2015-01-06 21:27 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

> >
> >
> > - przy redukcji CFI do IBCC nadal jest k=2 (ale może tylko w mojej
> > aktualnej lokalnej wersji ;)
> >
> > Tak, ktoś to musi jeszcze wprowadzić. Pozostawiam intro Bartkowi.
>
> >
> > -
> >
> > Przykład templatu orbit-finite z kolorowaniem grafów atomami (Example
> > 3). W dalszej części intro jest podany template skończony, który mu
> > odpowiada. Rozumiem, że on jest taki (relacje bez jednej pary), bo tak
> jest
> > łatwiej go opisać, ale trochę się obawiam, że dla czytelników bez
> > doświadczenia z CSP, to może być niejasne tzn. skąd on się bierze i
> > dlaczego te relacje wystarczą do wyrażenia oryginalnego problemu.
> Niestety
> > nie mam pomysłu jak to rozjaśnić
> >
> > Myślę, że tu można rozjaśnić opisując, jak przerobić instancję nad
> starym
> templatem na nową instancję.
>
> >
> > -
> >
> > We show that an instance of IBCC naturally defines a CSP instance over
> > a locally finite template:
> > 1) Moim zdaniem dla ludzi myślących "normalnie" ta konstrukcja nie
> > opisuje templatu lokalnie-skończonego, ale skończony: wartościamy są
> > bijekcje pomiędzy skończonymi grafami, takich bijekcji jest skończenie
> > wiele itd. Dopiero komentarz poniżej opisuje jak można w tym zobaczyć
> > template orbitowo-skończony.
> >
> > Rozumiem, że chodzi Ci o template skończony, składający się dokładnie z
> tych relacji, które pojawiają się w ustalonej (skończonej) instancji?
>

Mi chodziło nawet o "zmapowany" template.

Mi się wydaje, że naturalne jest to, że widzi się te skończone "małe" grafy
jako "nowe" obiekty, których jest (wszystkich możliwych) skończenie wiele.
Grafu G_c czytelnik nie widzi jako zbudowanego z wierzchołków G...

Ale wszystko w sumie jedno ;) Chyba zgadzamy się, że ten przykład jest
bardzo niejasny.



> Tak, owszem, jest. (Tu pojawia się jeden problem formalny – wg definicji,
> instancja powinna mieć określony zbiór dopuszczalnych wartości [domain] –
> a
> tu tego nie określamy. A gdybyśmy go określili, to by wyszła instancja
> właśnie nad tym templatem skończony, a nie tym nieskończonym).
>
> >
> > -
> >
> > 2) Ponadto, skoro czytelnik w naturalny sposób widzi IBCC jako
> > instancję nad skończonym templatem, to myśli sobie: "OK, skończony
> template
> > wystarczy" i ten przykład nie dowodzi użyteczności naszych templatów. Z
> > tego co ja rozumiem (nie wiem, czy poprawnie) IBCC nie można zdefiniować
> > jako instancji nad skończonym templatem przy pomocy LFP i dlatego ten
> > skończony template nie jest ok i potrzebujemy nieskończonego?I to jest
> niby
> > zasugerowane wcześniej... Ale nie wiem, czy to nie jest ciut zbyt zbyt
> > skomplikowane.
> >
> > To prawda, to dla mnie to jest mega skomplikowane i niejasne. Po co nam
> template nieskończony, skoro możemy mieć ten skończony? LFP nie robi
> różnicy, czy produkuje instancję nad jednym czy drugim templatem, bo te
> instancje wyglądają identycznie.


Ale wyprodukować instancji nad "zmapowanym" templatem LFP nie może?

**Comment by szymtor** [comment]
Nad zmapowanym nie może. Potencjalnie jest możliwe ze może sobie jakoś
inaczej poradzić ale nie wiem jak (chyba wiem jak w przypadku gdy jest
porządek liniowy na kolorach).

**Comment by bklin** [comment]
Jest taka opcja, żeby Example 5 po prostu wyrzucić. Tekst, który go poprzedza jest co prawda dosyć "wishy washy", ale czytelnik po obejrzeniu co się wcześniej działo z k-kolorowaniem jakoś może mętnie zrozumie że o coś nam chodzi, nawet jeśli nie do końca zrozumie o co. Jeżeli Example 5 ma więcej zamącić niż rozjaśnić, to może lepiej żeby go nie było.

**Comment by szymtor** [comment]
Hej,

Napisałem nową motywację w intro, w branchu intro (nie mam jej w 100% przemyślanej). Przeczytajcie i atakujcie!

P.S. Asia – Bartek słusznie zauważył, że termin "order-invariant" nie jest najlepszy, jako że funkcjonuje już w teorii modeli skończonych, i oznacza coś dokładnie odwrotnego:)

**Comment by ochremiak** [comment]
Hej!

Myślałam o intro i wydaje mi się, że dobra byłaby taka struktura (to
głównie poprzestawianie tego co tam już jest):

DOTYCZĄCE ORBIT-FINITE INSTANCES
- przykłady z instancjami orbit finite
- co to jest CSP
- nasze przykłady nie wpadają w mainstream, bo instancje są nieskończone,
ale można je skończenie prezentować więc są ok
- pokazujemy, że są rozstrzygalne przy pomocy pestova
- prezentujemy technikę obniżenia złożoności (+ lower bounds Eryka?)

DOTYCZĄCE FINITE INSTANCES
- przykłady finite instances (kolorowanie i CFI)
- CSP klasyczne zajmuje się skończonymi rzeczami z naciskiem na złożoności
charakteryzowaną przez polimorfizmy (taki paragraf jest)
- nasz aim to translate those results (tylko unikajmy może słowa "basic")
do przypadku templatów orb-skończonych
- udaje nam się to zrobić :)  (teorię alg + charakteryzację efektywną kiedy
algorytmy działają)
- ponadto umiemy redukować do skończonych templatów
- ale... templaty orb-skończone też mają głęboki sens ;) i tu wszystkie
motywacje dlaczego

2015-01-07 18:53 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

**Comment by bklin** [comment]
Wykasowałem z intro starą część o LFP (uwaga: zniknął m.in. przykład IBCC) i dostosowałem do struktury opisanej przez Asię powyżej.

Brakuje tam jeszcze podsumowania sekcji Szymka o LFP-motywacji; to powinno zająć kilka wierszy.
