### ISSUE TITLE
Przygotowania sekcji; Asizacja

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#13]
Hej, przechodzę przez artykuł i wykonując następujące czynności:

1) uzgadnianie notacji. Przy okazji – zamiast order-invariant proponuję order-preserving.
2) dodawanie na początku sekcji tekstów, które tłumaczą, co będzie się działo.
3) przygotowywanie do wywalania do apendiksu. Czyli, upewnienie się, że duże kawałki będzie można wywalić, a pozostanie przynajmniej sformułowanie lematu lub stwierdzenia, którego te kawałki dotyczyły.

Chciałem to zrobić z Asizacją, ale nie do końca wiem co tam się dzieje. Np. do czego służy Proposition 11? Poza tym, z Asizacją jest taki problem, że piszemy tam o rzeczach ekwiwariantnych, podczas gdy – jak rozumiem – właściwie chcemy wykorzystać to raczej do order-preserving.
Inna rzecz – z tego co pamiętam, w końcu nie trzeba zakładać, że termy są liniowe, a w dowodzie jest takie założenie.

Asia, czy mogłabyś wykonać punkty 1,2,3 w asizacji?

**Comment by szymtor** [comment]
Jeszcze jedna rzecz, którą wykonuję: 
4) Reformatuje paragrafy, tak, żeby wiersze miały ≤60 kolumn. To jest przydatne, żeby łatwiej było śledzić zmiany w commitach (żeby paragraf nie był cały w jednym wierszu).

**Comment by ochremiak** [comment]
Jasne. Zajmę się tym. Wracam dziś wieczorem i od jutra 100% mojej uwagi
jest skupione na artykule.

Asia

2015-01-10 15:07 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:
