### ISSUE TITLE
Compactness lemmas

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#15]
Zrobiłem przed chwilą takie rzeczy:
* w b81f906788c377068589b644fd4c70cffd9fcd2d: Change order of sections, replaced some sections by subsections etc.
* w 45060f9e17b683d29b0955cace3b4e6a33760112:
“Finite instances” is now a section (sec:fininst) which comprises three
subsections:
** “Algebra” (sec:algebra) in file algebra
[with a subsubsection “Cores” (sec:cores) in file cores]
** “Compactness” (sec:compactness) in file fininst
** “Squashing templates” (sec:atlas) in file atlas
* w 0300ff61d9e425f1633a6d1e2c24b01c291791d8 Two compactness lemmas are merged into one corollary {for:compactness}
which is placed in sec:erykery, after the main compactness lemma.
* jeszcze małe zmiany w b6f992c68f2f27b3d0abe2103bed3ca2cc76d14f.

Asia:
Przy okazji trzeciej zmiany, zauważyłem, że te dwa lematy o zwartości były jednak różne: Twój mówił o podinstancjach, mój o podstrukturach indukowanych. Każda podstruktura indukowana jest podinstancją (w constrained instance), a nie odwrotnie, więc Twój wariant jest ogólniejszy. Jest jeden problem, że podinstancja jest zdefiniowana dopiero później. Póki co, jeszcze nie naprawiłem tego problemu (stąd ten issue). Zacząłem się zastanawiać, czy Ty potrzebujesz podinstancji, czy podstruktury indukowanej w swoim dowodzie. I stwierdziłem, że nie wiem czego potrzebujesz w Proposition[prop:pol]. Myślę, że w tym dowodzie przydałoby się napisać co jest potrzebne – czy te F_E(T_i) są podinstancjami F_E(T) czy co. Poza tym, odkryłem (i częściowo zmieniłem), że templaty często się nazywają \str A, tak jak atoms. Jeszcze jedna rzecz – czasem piszesz, że template jest strukturą relacyjną. Ja wolę tak nie mówić – w preliminarisach jest napisane, że template jest czymś innym niż str.rel, choć można go tak potraktować.

**Comment by ochremiak** [comment]
W dowodzie Proposition[prop:pol] potrzebne są podinstancje. Przypuśćmy, że
interesuje nas polimorfizm arności 3, który nie spełnia żadnych
identyczności. Mamy łańcuch wstępujący podtemplatów (po prostu rozważamy
coraz więcej relacji z oryginalnego templatu i tą część dziedziny, którą
„pokrywają”) i konstruujemy z nich kolejne podinstancje o dziedzinach
T_1^3, T_2^3 itd. Te dziedziny się w sobie zawierają, ale wyposażamy je w
coraz więcej konstreintów, bo coraz więcej relacji się pojawia.


Podinstancja to podstruktura tylko nie indukowana, więc może tak z tego
wybrnąć? Tzn. sformułować corollary dla podstruktur?


Z Twoimi pozostałymi uwagami się zgadzam i to pozmieniam tzn. wyjaśnię i
nie będę pisać, że template to struktura relacyjna.

2015-01-13 16:53 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

**Comment by szymtor** [comment]
>
> Podinstancja to podstruktura tylko nie indukowana, więc może tak z tego
> wybrnąć? Tzn. sformułować corollary dla podstruktur?
>
>
Brzmi jak dobry pomysł. Mam jeszcze taki problem, że żeby to była prawda,
to przynajmniej potrzeba, że by te podinstancje skończone pokryły tę dużą
zarówno wierzchołkowo, jak i krawędziowo. Ale jeszcze nie wiem, czy to
wystarczy. W każdym razie wydaje się, że lemat będzie miał trudniejszy
dowód niż w obu przypadkach z osobna...

**Comment by szymtor** [comment]
OK, udało się uogólnić ten wniosek i go udowodnić jako wniosek z lem:hom-compact,
choć jego dowód jest dłuższy niż dowód lematu. Ale pozostawiam jako wniosek, bo chcę żeby koncepcyjnie zwartość była źródłem wszystkich dobrych własności templatów locfin. Zamykam issue (ale, jak zwykle, pisać można tu dalej).

**Comment by ochremiak** [comment]
Hej!

Ja nie rozumiem Twojego dowodu.

1) Czy nie jest tak, że pojęcie podstruktura i podinstancja to to samo (z
dokładnością do isolated nodes)? Czyli mój pierwotny dowód działa?

2) Dlaczego warunek, że I_n sumują się do I nie wystarczy? Czy to nie
znaczy właśnie tyle, że I_n pokrywają I wierzchołkowo i krawędziowo?

4) W moim zastosowaniu tego wniosku warunek, że każda skończona indukowana
podstrukutra jest pokryta przez jakieś I_n nie jest spełniony np. gdy
któryś wierzchołek należy do wszystkich relacji.

3) Nie rozumiem pierwszego paragrafu dowodu. Jak rozszerzasz homomorfizm
f_n?


2015-01-13 22:18 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

**Comment by szymtor** [comment]
Hej,


> 1) Czy nie jest tak, że pojęcie podstruktura i podinstancja to to samo (z
> dokładnością do isolated nodes)?


Masz rację, nie zauważyłem tego.


> Czyli mój pierwotny dowód działa?
>

Właśnie sobie zdałem sprawę, że nie czytałem Twojego dowodu...
tylko zobaczyłem, że nie używa lematu Bartka i arogancko stwierdziłem, że
na pewno się da z tamtego. Całkiem fajny Twój dowód (i w sumie bardzo
podobny do mojego ostatniego).


>
> 2) Dlaczego warunek, że I_n sumują się do I nie wystarczy? Czy to nie
> znaczy właśnie tyle, że I_n pokrywają I wierzchołkowo i krawędziowo?
>

Masz rację, jednak wystarczy, Twój dowód mnie przekonał. Chyba byłem już
zbyt zmęczony.


>
> 4) W moim zastosowaniu tego wniosku warunek, że każda skończona indukowana
> podstrukutra jest pokryta przez jakieś I_n nie jest spełniony np. gdy
> któryś wierzchołek należy do wszystkich relacji.
>

Faktycznie, tego też nie zauważyłem.

>
> 3) Nie rozumiem pierwszego paragrafu dowodu. Jak rozszerzasz homomorfizm
> f_n?
>

Rozszerzam przez walnięcie ⊥ dla wszystkich x∉Dom f_n.
Faktycznie, jest mały problem – struktura T^\bot była źle zdefiniowana,
R(\bar x) powinno zachodzić dla wszystkich krotek które zawierają
⊥ na którejś współrzędnej. Ta struktura przestaje być lokalnie skończona...
Ale i tak każdy i∈I ma tylko skończenie wiele możliwych wartości przy
homomorfizmie T^\bot.

Więc niestety nie domyka się z lematem Bartka, więc tylko straciłem
niepotrzebnie czas bo Twój dowód jest równie dobry.....

Może zamiast obydwu lematów (Bartka i tego) zostawimy jeden o takiej treści:

Niech hom*(I,T) to zbiór wszystkich homomorfizmów
f:I'→T, gdzie I' jest konstrejnowaną podstrukturą I (niekoniecznie
indukowaną).
Wtedy hom*(I,T) jest zwartą podprzestrzenią przestrzeni I→T∪{⊥}.

a) Czy ten lemat jest prawdziwy?
b) Czy uogólnia wszystkie lematy?

**Comment by szymtor** [comment]
Lemat w wersji, którą zaproponowałem, jest fałszywy.

Sorry za zamieszanie. Niepotrzebnie się zajmuję bzdurami.
Ale jak macie pomysł na one lemma to rule them all to napiszcie.

2015-01-14 8:31 GMT+01:00 szymon <szymtor@gmail.com>:

**Comment by ochremiak** [comment]
Też myślałam, że ta struktura przestaje być lokalnie skończona. Ale chyba
nie... Mamy skończone R arności n w T. Ta relacja "dotyka" skończonego
kawałka T_R templatu. Nowe R to będzie (T_R \cup {⊥} )^n.

Teraz moim zdaniem można zostawić stary lemat bartka i dodać corollary:

Corollary 5. Let I be a structure and let I_0  I_1  I_2 ... be
an ascending sequence of substructures of I, such that they sum to I. There
is a homomorphism f : I \to T if and only if
for each n there exists a homomorphism f_n : I_n \to T. If
all the f_n extend a single homomorphism f_0 : I_0 \to T, then
so does f.

Zgadzasz się?

Ja to mogę pozmieniać.

2015-01-14 8:40 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

**Comment by szymtor** [comment]
Super, dzięki!

Sz.

2015-01-14 9:03 GMT+01:00 ochremiak <notifications@github.com>:

**Comment by ochremiak** [comment]
Jednak dorzucenie tych tupli do relacji nie wystarczy. Próbowałam jeszcze
wymyślić jak to naprawić, ale nie umiem. Co Ty na to, żebym wróciła do
mojego poprzedniego dowodu i umieściła to jako lemat w sekcji Algebra - tam
gdzie Ty tego potrzebujesz?

2015-01-14 9:33 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

**Comment by szymtor** [comment]
OK.

2015-01-14 18:09 GMT+01:00 ochremiak <notifications@github.com>:
