### ISSUE TITLE
\str A na oznaczenie struktury relacyjnej

### ISSUE THREAD

**Issue by ochremiak** [szymtor/locfin#18]
Czy w rozdziale o algebrze tak zostanie?

**Comment by szymtor** [comment]
Proponuje przedefiniować macro \atoms na \textrm{Atoms}. To będzie
spójniejsze z nasza notacja, bo Atoms to nie struktura (raczej nośnik).

**Comment by ochremiak** [comment]
jestem za

2015-01-14 11:03 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

> Proponuje przedefiniować macro \atoms na \textrm{Atoms}. To będzie
> spójniejsze z nasza notacja, bo Atoms to nie struktura (raczej nośnik).

**Comment by szymtor** [comment]
Zrobione.
