### ISSUE TITLE
sekcja o LFP

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#19]
Sytuacja z LFP wygląda słabo – poniżej sprawozdanie. 

Myślałem nad następującymi rzeczami na temat logiki: 
* Pokazać, jak elegancko powtórzyć nasz dowód z poprzedniego artykułu. To wymaga zdefiniowania P-patched structures i TMA lub LFP. Ważny element dowodu pozostaje bez zmian: jeżeli TMA rozstrzyga Iso to algorytm (k,l)-konstystencji też. Wszystkie pozostałe kroki się bardzo upraszczają: Iso jest równoważne CSP(T_P), gdzie T_P to template locfin, który ewidentnie ma Malcewa. Ma on bounded-width wtw gdy ma majority (tu korzystamy z części dot. zwartości), i to umiemy rozstrzygać (korzystając z Erykery).
* To co jest w tej chwili napisane w ostatniej sekcji, czyli że to, czy jakaś logika L (np. LFP+Rk) chwyta PTime na strukturach linearly P-patched "zależy" od algebry polimorfizmów templata T_P. Trzeba zdefiniować te same rzeczy co powyżej. Wada tej historii jest taka, że ta obserwacja do niczego nie może doprowadzić. (Jeżeli ktoś chciałby badać, czy LFP+Rk≠Ptime, to nie zrobi tego poprzez badanie polimorfizmów)
* Można napisać, że na mocy our general method, charakteryzacja za pomocą tożsamości liniowych skończonych templatów, które można rozwiązać np. w LFP+Rk natychmiast podnosi się do rozstrzygalnej charakteryzacji tych alfabetów (lub patchów) P, dla których LFP+Rk chwyta PTime na linearly P-patched structures. Wada tego jest taka, że ludzi nie interesuje w tej chwili charakteryzacja, nad jakimi alfabetami linearly P-patched structures LFP+rk chwyta PTime, tylko czy w ogóle istnieje taki alfabet P, że nie chwyta. A zamiast rozważać pytanie, czy LFP+Rk potrafi rozwiązać każdy template postaci T_P, łatwiej zadać pytanie, czy LFP+Rk potrafi rozwiązać każdy skończony template Malcewowski. Wydaje mi się, że potrafię łatwo pokazać (bez mowy o żadnych locfin) że odpowiedź na to pytanie jest równoważne temu, czy LFP+Rk chwyta PTime na linearly P-patched structures.
* Można bełkotać na temat tego, że niektóre problemy (takie jak to 2-kolorowanie grafów lub Iso Bounded Color Classes) naturalnie (za pomocą LFP redukcji) redukują się do CSP nad templatem locfin-orbfin, a do templatu skończonego nie widać jak to zrobić.

Jeśli nie jesteście przekonani do któregoś z powyższych pomysłów, to proponuję odpuścić sobie LFP.
Sz.

**Comment by bklin** [comment]
Odpuszczenie sobie LFP jest bliskie memu sercu, ale ma pewną wadę: w abstrakcie napisaliśmy o Descriptive Complexity Theory. Wydaje mi się że jeden marny przykład z Intro nie broni tego stwierdzenia. Jak je obronimy?

**Comment by ochremiak** [comment]
Mi się chyba najbardziej podoba punkt 1) w wariancie definiowanie LFP i
P-patched structures (bez TMA).
- Widać wyraźnie gdzie stosują się główne wyniki artykułu.
- Template orbfin pojawia się w miarę naturalnie i występuje w
sformułowaniu twierdzenia.
- To twierdzenie uogólnia dwa znane wyniki Descriptive Complexity, więc
może to wystarczy do obrony stwierdzenia w abstrakcie?
A nie można się ograniczyć do P-patched graphs, żeby były łatwiejsze
definicje?

2015-01-14 19:58 GMT+01:00 bklin <notifications@github.com>:

**Comment by szymtor** [comment]
Bartek, a Ty co myślisz o powyższych punktach?

**Comment by bklin** [comment]
Żaden z nich mnie jakoś super nie ekscytuje, ale moim zdaniem coś napisać powinniśmy. Wydaje mi się, że punkt 1) bez TMA wymaga wprowadzenia najmniejszej liczby nowych pojęć?

Jeżeli punkt 1) da się opisać gdzieś na 3/4 strony, to bym był chyba  za tym. W przeciwnym przypadku zostaje bełkot, czyli punkt 4).

ALE: jestem w tej sprawie zdecydowanie najmniej kompetentny z nas i nie mam mocnego zdania technicznego, tylko PRowe.
