### ISSUE TITLE
Co naprawdę robi nasz artykuł

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#20]
Proponuję wątek na temat tego, o czym naprawdę jest nasz artykuł. 
(Co prawda, wiele razy to już omawialiśmy, ale ja jeszcze nie ułożyłem sobie tego w głowie).

Więc wydaje mi się, że:
* Przede wszystkim, rozważamy templaty lokalnie skończone. (To, że są zbudowane z atomów, i że są orbitowo skończone, jest mniej istotne).
* Dla templatów locfin mamy zwartość. Ta prosta obserwacja pozwala nam przenosić w prosty sposób wiele istniejących wyników (algebra i dualność inv-pol, charakteryzacje algorytmów za pomocą tożsamości, implikacje takie jak Malcev+bounded width→majority).

* Dodatkowo, jak template jest orbitowo-skończony, to potrafimy: zbadać czy ma jakiś polimorfizm, obliczyć jego rdzeń.
* Poza tym, potrafimy rozwiązywać instancje orbitowo skończone nad templatami locfin. (Template nie musi być orbitowo skończony, by i tak ta instancja używa tylko skończenie wielu jego orbit).
* W przypadku skończonego templatu T, mamy optymalną złożoność CSPOrbFin(T).

Czy zgadzacie się z takim ujęciem naszego artykułu?

**Comment by ochremiak** [comment]
Ja się zgadzam.

Twój opis kładzie nacisk na instancje skończone. Celowo?

2015-01-14 19:27 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

**Comment by bklin** [comment]
Podoba mi się ta historia, ale kolejność rzeczy w naszym artykule trochę jej nie odpowiada. Chcemy coś przestawiać?

Można by zacząć przestawiać, ale moim zdaniem te przykłady na początku budzą zainteresowanie, dobrze by je tam mieć jako reklamę. Nawet ludzie mający gdzieś CSP powinni to przeczytać bez wstrętu.

**Comment by szymtor** [comment]
Nacisk na instancję skończone położyłem dlatego, żeby sobie uświadomić,
że ta część nie ma nic wspólnego z atomami. Jest ryzyko, że jest to szeroko
znane/trywialne, więc powinniśmy zbadać, czy coś takiego się gdzieś nie
pojawia w literaturze. Tak czy siak, chyba powinniśmy zaznaczyć w artykule,
że te zjawiska są bezatomowe.

Jeżeli chodzi o część atomową, to myślę, że warto sformułować pytanie
otwarte o to, czy CSPOrbFin jest rozstrzygalny dla templatów nie locfin?



2015-01-15 0:06 GMT+01:00 bklin <notifications@github.com>:

**Comment by szymtor** [comment]
Znalazłem taki artykuł (
http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.9.6977, z
konferencji SAC 2005) który jakoś motywuje badanie
instancji nieskończonych.

2015-01-15 9:07 GMT+01:00 szymon <szymtor@gmail.com>:

**Comment by ochremiak** [comment]
W temacie tego, czy nasze wyniki nie wynikają w sposób trywialny z czegoś
znanego:
Znalazłam wczoraj taki artykuł Bodirskiego
http://arxiv.org/pdf/0809.2386.pdf
Na przykład Corollary 3 daje podobną do naszej charakteryzację strict
bounded width (dla templatów omega-kategorycznych i skończonej sygnatury).

2015-01-15 9:22 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

**Comment by bklin** [comment]
Ja znam tych autorów, już ich spytałem co dalej się działo z tym kierunkiem.

**Comment by bklin** [comment]
Dobra, to ja robię tak:

- z rozdziału o Erykerii usuwam orbitową skończoność templatu. Niektóre twierdzenia się tam troszkę osłabią, ale nieistotnie z naszego punktu widzenia.
- przerabiam trochę Intro tak, żeby przekazać komunikat że lokalna skończoność templatu jest bardziej fundamentalna niż orbitowa skończoność.

Jak teraz przeglądacie literaturę to jednocześnie planujcie Related Work, bo to trzeba napisać. Zapewne na końcu Intro. Pewnie nie musi być długie.
