### ISSUE TITLE
polymorphisms and identities

### ISSUE THREAD

**Issue by bklin** [szymtor/locfin#21]
Czy te faleczki (\approx) w identycznościach spełnianych przez polimorfizmy to jakiś standard w literaturze, czy też to nasz wynalazek?

Bo ja nie widzę powodu dlaczego nie miałyby to być po prostu znaki równości.

**Comment by szymtor** [comment]
Zdaje się ze to niestety norma. Tez nie rozumiem po co, głosuje za =.

**Comment by ochremiak** [comment]
To norma, więc dlaczego mamy wprowadzać własną notację? ;)

2015-01-14 22:25 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

> Zdaje się ze to niestety norma. Tez nie rozumiem po co, głosuje za =.

**Comment by bklin** [comment]
E tam norma. Oto wygóglowane równości zamiast faleczek:

Bodirsky: (góra strony 21)
http://www.math.tu-dresden.de/~bodirsky/Graph-Homomorphisms.pdf

Chen-Dalmau-Grussien:     (dół strony 11)
http://arxiv.org/pdf/1104.4993.pdf

A. Kazda: (dół strony 2)
http://arxiv.org/pdf/0912.4035.pdf

**Comment by ochremiak** [comment]
Bartek, Ty powywalasz definicje polimorfizmów i E-polimorfizmów z miejsc
gdzie są obecnie?

2015-01-14 22:32 GMT+01:00 bklin <notifications@github.com>:

>
> E tam norma. Oto wygóglowane równości zamiast faleczek:
>
> Bodirsky: (góra strony 21)
> http://www.math.tu-dresden.de/~bodirsky/Graph-Homomorphisms.pdf
>
> Chen-Dalmau-Grussien: (dół strony 11)
> http://arxiv.org/pdf/1104.4993.pdf
>
> A. Kazda: (dół strony 2)
> http://arxiv.org/pdf/0912.4035.pdf
>
> On 14 Jan 2015, at 22:26, ochremiak wrote:
>
> > To norma, więc dlaczego mamy wprowadzać własną notację? ;)
> >
> > 2015-01-14 22:25 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:
> >
> > > Zdaje się ze to niestety norma. Tez nie rozumiem po co, głosuje za =.

**Comment by szymtor** [comment]
Ja stawiam hipotezę ze jest różnica miedzy równością f(x,y)=g(x,y) a
tożsamością. Równość dotyczy konkretnych elementów x,y, albo jest
poprzedzona kwantyfikatorem uniwersalnym (tak jest w przytoczonych przez
Ciebie przykładach). W tożsamości kwantyfikacja jest implicite. Nie mowię,
ze to jest bardzo sensowne.

**Comment by bklin** [comment]
Już nie dzisiaj, ale powywalam. Ale nie będę wywalał takich rzeczy jak near-unanimity, one chyba pasują tam gdzie są.

**Comment by ochremiak** [comment]
Tak. Near unanimity itd. niech zostanie gdzie jest.

2015-01-14 23:14 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
OK, jednak już wywaliłem E-polimorfizmy z sekcji o algebrze. I zostawiłem te faleczki, niech już będzie.
