### ISSUE TITLE
Squashing

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#24]
Przeczytałem dziś artykuł. Mam dużo uwag do wszystkich sekcji, tu napiszę te do squashingu, resztę spróbuję wprowadzić sam. Użytkownik "ochremiak" jest asignee tego issue :)

* Zamiast dwóch pierwszych paragrafów: In this section, we prove the following. Theorem x: for every locfin T there is a finite \hat T such that for every finite instance I over there is a finite instance \hat I over \hat T, such that I maps to T iff \hat I maps to \hat T. Moreover, for every set of linear identities E, if T admits E-polymorphisms, then \hat T admits E-polymorphisms. 

* Wywalić wszystko o izomorfizmach, mapach, atlasach. Dla elementu x o suporcie {a1,...,an} z a1<a2<...<an, zdefiniować [x] jako x z atomami a1,...,an zastąpionymi przez atomy 1,...,n.

* Zdefniować U_x jako unarny predykat zdefiniowany przez pp-formułę (gwiazda(I,x), x), gdzie gwiazda(I,x) to sąsiedztwo x w I.

* sub-instance → subinstance, podobnie z sub-template

* Wywalić paragraf o "The construction presented above does not depend on the fact that the atoms are equipped with a total order".

* Przed powyższym paragrafem napisać: "This proves the first part of Theorem x. We now prove the second part."

* W lemacie 24, zdanie "Since the domain of F_E(T) is a disjoint union of sets of the form T^n, it is possible to extend this solution" → czemu?

* Wywalić Theorem 25. Zamiast proof, "we now finish the proof of Theorem x".

* Zamiast A\models E, "A satisfies the identities in E" (2 razy)

**Comment by ochremiak** [comment]
Część zrobiona. Jutro skończę.
