### ISSUE TITLE
Related work

### ISSUE THREAD

**Issue by bklin** [szymtor/locfin#26]
Proponuję tu wrzucać artykuły, które możemy lub powinniśmy wymienić.

Zaczynam:
Hubie Chen, "Periodic constraint satisfaction problems: Polynomial-time algorithms", CP2003
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.10.8442&rep=rep1&type=pdf
"Periodyczne" nieskończone instancje a'la Freedman, dwie klasy tractable (w P)

**Comment by ochremiak** [comment]
Przesyłam jakiś przegląd tego co się dzieje u Bodirskyego. Pewnie poza tym
można przytoczyć jego habilitację.

Template – nieskończony, nad skończoną sygnaturą, (zachowuje się dobrze gdy
jest omega-kategoryczny)

Tłumaczenie podstawowych wyników algebraicznych na struktury
omega-kategoryczne:

1) “CORES OF COUNTABLY CATEGORICAL STRUCTURES”   MANUEL BODIRSKY

2) M. Bodirsky and J. Neˇsetˇril. “Constraint satisfaction with countable
homogeneous templates.”  (show that the computational complexity of
CSP(Gamma) for countable homogeneous Gamma is determined by the clone of
polymorphisms of Gamma)

3) “TOPOLOGICAL BIRKHOFF” MANUEL BODIRSKY AND MICHAEL PINSKER  (To jest
nowa paraca z 2012 - For countable omega-categorical Gamma, the complexity
of CSP(Gamma) only depends on Pol(Gamma) viewed as a topological clone.)

The universal-algebraic approach has been used to obtain complete

complexity classifications for large classes of ω-categorical templates:

1) M. Bodirsky and J. K ́ara. The complexity of temporal constraint
satisfaction problems.

2) M. Bodirsky and M. Pinsker. Schaefer’s theorem for graphs

Ramsey Theory:

1) “REDUCTS OF RAMSEY STRUCTURES” MANUEL BODIRSKY AND MICHAEL PINSKER
(Applying
techniques from Ramsey theory to obtain a complexity classification of
CSP(Gamma) for reducts of ramsey structures.)

Charakteryzacja kiedy algorytmy działają:

1) “Datalog and Constraint Satisfaction with Infinite Templates” Manuel
Bodirsky and V ́ıctor Dalmau






2015-01-15 22:10 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
A co się dzieje z tym wątkiem? W jakim jesteśmy stanie?

**Comment by eryxcc** [comment]
Ja znam takie referencje:

- że układy równań są MODkL zupełne [ http://link.springer.com/article/10.1007%2FBF01374526 ]

- wynik trochę w stylu naszego lower boundu: http://www.sciencedirect.com/science/article/pii/S0019995886800092 (ciekawie wygląda http://link.springer.com/chapter/10.1007/978-1-4615-3422-8_30 ale nie udaje mi się do niego dobrać, także nie wiem, czy rzeczywiście ciekawe)

**Comment by bklin** [comment]
Napisałem related work, zobaczcie czy się Wam podoba i zmieniajcie jeśli chcecie.

Dwa pytania:
- tuż przed Tw. 26 jest cytowanie pracy "jeavons". Nie wiem o jaką pracę chodzi, niech ktoś to wpisze w bib.bib.
- czy są jakieś kanoniczne prace o CSP których nie cytujemy, a powinniśmy? Szczególnie mnie drażni pozbawiony cytowań akapit we wstępie tuż po definicji CSP: (a) gdzie napisano że złożoność CSP zależy od polimorfizmów? (b) skąd wiadomo że Maltsev implikuje tractability? (c) skąd wiadomo że brak cyclic implikuje NP-zupełność?

**Comment by ochremiak** [comment]
2015-01-19 14:36 GMT+01:00 bklin <notifications@github.com>:

> Napisałem related work, zobaczcie czy się Wam podoba i zmieniajcie jeśli
> chcecie.
>
> Dwa pytania:
>
>    - tuż przed Tw. 26 jest cytowanie pracy "jeavons". Nie wiem o jaką
>    pracę chodzi, niech ktoś to wpisze w bib.bib.
>
> Chyba JEAVONS, P., COHEN, D., AND GYSSENS, M. 1997. Closure properties of
constraints. J. ACM 44, 4, 527–548.

Zaraz dorzucę do biblio.


>
>    - czy są jakieś kanoniczne prace o CSP których nie cytujemy, a
>    powinniśmy? Szczególnie mnie drażni pozbawiony cytowań akapit we wstępie
>    tuż po definicji CSP: (a) gdzie napisano że złożoność CSP zależy od
>    polimorfizmów?
>
> No to chyba ten sam Jeavons?


>
>    - (b) skąd wiadomo że Maltsev implikuje tractability? (c) skąd wiadomo
>    że brak cyclic implikuje NP-zupełność?
>
> To jest skomplikowane. Bo Bulatov i spółka udowodnili, że brak Tylor
implikuje NP zupełność, a Barto i Kozik, że brak Tylor to to samo co brak
cyclic. Wrzucić to wszystko?

**Comment by ochremiak** [comment]
Dobra. Wrzuciłam Jeavonsa i trzy cytowania do cyclic term we wstępie. Z
Maltsevem nie wiem.

2015-01-19 17:26 GMT+01:00 Joanna Ochremiak <joanna.ochremiak@gmail.com>:

**Comment by ochremiak** [comment]
Czemu bibliografia jest niealfabetycznie?

2015-01-19 18:04 GMT+01:00 Joanna Ochremiak <joanna.ochremiak@gmail.com>:
