### ISSUE TITLE
Uwagi do Compactness

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#27]
* Jaki tytuł?

* W definicji few subpowers, chyba powinno być "s_B(n) is bounded above by a polynomial" (B zamiast A)?

**Comment by bklin** [comment]
On 16 Jan 2015, at 09:06, Szymon Toruńczyk wrote:

> 	• Jaki tytuł?

Proponuje "From finite to locally finite templates"

**Comment by szymtor** [comment]
To może squashing -> from locally finite to finite templates?

**Comment by bklin** [comment]
Też o tym pomyślałem. Brzmi fajnie, chociaż kompletnie myląco, bo tak naprawdę w obu sekcjach transfer twierdzeń idzie w tę samą stronę. Ale jestem za.

**Comment by szymtor** [comment]
Tak. Ale transfer polimorfizmow idzie w rozne strony.

**Comment by ochremiak** [comment]
Mi się podoba. Zmienię w obu sekcjach.

**Comment by bklin** [comment]
MNIE! MNIE się podoba!

(c) Paweł Urzyczyn.
