### ISSUE TITLE
Revolution in Intro

### ISSUE THREAD

**Issue by ochremiak** [szymtor/locfin#29]
Kilka uwag:

"Our Examples 1 and 2 do not fit the mainstream development
of CSP theory..." potem pojawiają się cztery "opisy" naszych instancji:
- że są orbit-finite i built of atoms
- finitely presented
- defined by expressions
- definable
Wydaje mi się, że tych pojęć jest za dużo na raz. Może zrobić to tutaj nieformalnie i mówić o instancjach FO definiowalnych za atomami, czy coś w tym stylu. Tzn. użyć jednej nieścisłej charakteryzacji i w całym intro nie mówić o "orbit-finite" tylko o "definable"? Problem widzę tylko taki, że abstract mówi o orbit-finite.

Paragraf pod twierdzeniem Pestova chyba można wywalić, bo nie daje żadnych dodatkowych info skoro przytaczamy tw. eryka o Exp(C)?

locally finite jest dwa razy zdefiniowane

"In Section IV we lift some central results from classical
CSP theory to the setting of orbit-finite templates. Here, we
additionally restrict attention to locally finite templates, where
all relations are finite (although we still allow infinitely many
relations in a template)." 

Zmieniłabym na:

In Section IV we lift some central results from classical
CSP theory to the setting of locally finite templates.   (locally finite jest zdefiniowane wcześniej)

**Comment by szymtor** [comment]
Hej,

jednak myślę, że dobrze by było, gdybyś te zmiany wprowadzała na żywo.
Po zmianie w każdym paragrafie, rób commita. W ten sposób, będzie można na
bierząco dyskutować zmiany w pull requescie i cofać poszczególne małe itd.
Także, jeśli zdecydujemy się wrócić do mastera, to trzeba będzie te zmiany
tam przenieść z powrotem, i dobrze, żeby były podzielone na jak najmniejsze
moduły. Proszę też o w miarę informatywne opisy (więcej niż p),
choćby, czy zmiana dotyczy rewolucyjnej części, czy nierewolucyjnej.

**Comment by ochremiak** [comment]
ok

2015-01-17 12:35 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:
