### ISSUE TITLE
revolt w Erykerii

### ISSUE THREAD

**Issue by bklin** [szymtor/locfin#30]
Potrzebuję pomocy w Erykerii.

Zaczyna się w Lemma 9. Wszystko gra aż do charakteryzacji fixpointów akcji grupy. To, że one są ekwiwariantne wynika wprost z definicji. Ale dlaczego są definiowalne? Jak to najlepiej pokazać, jakieś pomysły?

**Comment by ochremiak** [comment]
Ale to nie jest tak, że definiowalność potrzebna jest dopiero w Lemacie 12?

2015-01-17 18:16 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
Moralnie powinno tak być. Ale po rewolucji, tak jak są teraz napisane preliminarisy, w ogóle nie umiemy powiedzieć o zbiorze "equivariant" jeżeli nie jest definiowalny.

**Comment by szymtor** [comment]
Aha. Tu się pewnie przyda jeden wniosek z wariantu dowodu Faktu o
quantifier elimination (pierwszy dowód, który właśnie zastąpiłem innym):

każdy ekwiwariantny podzbiór A^n jest definiowalny.

2015-01-17 18:34 GMT+01:00 bklin <notifications@github.com>:

**Comment by ochremiak** [comment]
Ale:
1) Bartek ma rację, że definicja ekwiwariant istnieje tylko dla zbiorów
definiowanych
2) W lemacie 9 instancja i template nie muszą być skończenie-orbitowe

2015-01-17 18:38 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

**Comment by szymtor** [comment]
To powinniśmy zdefiniować equivariant dla dowolnych zbiorów z działaniem grupy.
