### ISSUE TITLE
Jakie lower boundy?

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#31]
Pytanie do wszystkich:
Które lower boundy Eryka są ważne? Eryk, co Ty uważasz?
W wersji która teraz powstaje, jest tylko wynik ogólny. Czy myślisz, że inne zasługują na wspomnienie?

**Comment by eryxcc** [comment]
Wyniki dodatkowe są takie:
- że wystarczy tylko dwuatomowy zbiór atomów
- że dla czterech templatów o różnej złożoności wystarczą tylko najprostsze constrainty (tam jeszcze jest napisane, że jak constrainty są puste to problem staje się prosty, ale to nie musi być w głównym artykule)
- że dla 3CNF, NEXPTIME-zupełność otrzymujemy nawet w przypadku, gdy liczba orbit nieuporządkowanych jest ustalona, czyli że wzięcie porządku jest istotne, bo przekłada się to na złożoność

Jak dla mnie wszystkie są ciekawe, ale nie wiem, jak mamy z miejscem.

**Comment by szymtor** [comment]
Ja bym wspomniał te wyniki w jakimś remarku, tak jak to podsumował Eryk.

**Comment by bklin** [comment]
Wspomniałem w remarku.
