### ISSUE TITLE
linear/total order

### ISSUE THREAD

**Issue by ochremiak** [szymtor/locfin#34]
Chcemy mieć oba terminy?

**Comment by bklin** [comment]
Nie! Ale nie możemy się z Szymkiem zdecydować który lepszy, więc Ty musisz to rozstrzygnąć.

**Comment by ochremiak** [comment]
Nie znam Waszych argumentów. Ale mi się linear kojarzy z liczbami
naturalnymi, więc dałabym total ;)

To mało poważny argument, ale jeśli się zgadzasz, to zmienię wszędzie.

2015-01-18 9:05 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
Lejesz miód na moje serce!

**Comment by ochremiak** [comment]
To zmieniam zanim Szymon się obudzi ;)

2015-01-18 9:12 GMT+01:00 bklin <notifications@github.com>:

**Comment by szymtor** [comment]
NIEEEEEEEE


2015-01-18 9:16 GMT+01:00 ochremiak <notifications@github.com>:

**Comment by szymtor** [comment]
Problem jest taki, że w poprzednim artykule używaliśmy "linearly patched
structures" i już nic z tym nie zrobimy. Powinniśmy zatem pozostać przy
linear.

2015-01-18 9:18 GMT+01:00 Szymon Toruńczyk <szymtor@mimuw.edu.pl>:

**Comment by ochremiak** [comment]
Właśnie to zauważyłam ;) Linearly p-patched structures oczywiście nie
zmienimy, ale moim zdaniem porządek na atomach może być total, a na
patchach linear. Mi to nawet pasuje do wyobrażenia na temat total i linear
;)

Skoro może być "map" i "function", to może może być "total" i "linear"?

2015-01-18 9:19 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

**Comment by bklin** [comment]
Zaraz, chyba tutaj wychodzę na manipulancką szuję, bo coś mi się przypomina że zgodziłem się był na to "linear".

Przepraszam Asiu, jednak chyba linear.

**Comment by bklin** [comment]
Ja się na to zgadzam.

**Comment by szymtor** [comment]
Zgadzam się. Bo Dugald MacPherson na zmianę używa linear i total.

2015-01-18 9:24 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
Nie ma wstydu w robieniu czegoś co robi człowiek, który nazywa się Dugald MacPherson.

**Comment by ochremiak** [comment]
Konkluzja?

2015-01-18 9:26 GMT+01:00 bklin <notifications@github.com>:

**Comment by szymtor** [comment]
Moja własna konkluzja: jak chcesz, to możesz zamienić linear na total
wszędzie poza patchami.

Swoją drogą, używamy < a nie ≤, a normalnie order to ≤.

2015-01-18 9:27 GMT+01:00 ochremiak <notifications@github.com>:

**Comment by ochremiak** [comment]
Ja już sama nie wiem ;)

Bo "total order of the rationals" daje zero wyników w Googlu, a "linear
order of the rationals" 27 tysięcy

2015-01-18 9:28 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

**Comment by ochremiak** [comment]
Zmieniłam.

2015-01-18 9:31 GMT+01:00 Joanna Ochremiak <joanna.ochremiak@gmail.com>:
