### ISSUE TITLE
plan na dziś

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#35]
Co mamy do zrobienia?

* uspójnić tekst
* czytać
* napisać related work

Co jeszcze?

**Comment by bklin** [comment]
Ja nic nie widzę innego. Przy czym proponuję zacząć tak:

- ja czytam i uspójniam,
- Wy uzgadniacie related work.

Uzasadnienie: do related work potrzebna jest Asia, a potem jej nie będzie.

**Comment by ochremiak** [comment]
Ok. To ja porzucam czytanie i przejrzę Bodirskyego teraz.

Jaka decyzja w sprawie no-support?

2015-01-18 9:47 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
No pozytywna chyba?

Acha, Szymku, zanim co to może przejrzyj świeżym okiem swój wczorajszy wkład w IIB, z tym dowodem itd. Ja teraz czytam drugą połowę paperu.

**Comment by szymtor** [comment]
Ja popieram no support. Merguję.

Przejrzałem świeżym okiem, jest ok.




2015-01-18 9:53 GMT+01:00 bklin <notifications@github.com>:
