### ISSUE TITLE
sekcja o algebrze

### ISSUE THREAD

**Issue by bklin** [szymtor/locfin#36]
Przechodzę sekcję IV.A i mam pytania:

- czy Prop. 14 można sformułować tak: "every pp-definable relation on any relational structure is 
pp-definable by a finite formula"? Bez żadnych dodatkowych założeń o niczym? Bo tak to brzmi teraz.

- czy mogę na początku tej sekcji pozmieniać A --> I ,   B --> T,   a dopiero potem, w Prop 16, użyć liter B i C?

**Comment by szymtor** [comment]
* Brakuje założenia, że B jest locfin.
* Możesz.

2015-01-18 9:45 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
Kul!   A gdzie to założenie widać w dowodzie? W argumencie z compactness w dowodzie Lem. 15, czy jeszcze gdzieś?

**Comment by bklin** [comment]
Sorry, jakąś bzdurę napisałem poprzednio. Gdzie widać to założenie o locfin konkretnie?

**Comment by szymtor** [comment]
W tym, że chcemy zastosować lemat 15, do T=B. W lemacie 15 jest potrzebne
to założenie nt. T.

2015-01-18 10:05 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
OK, dzięki!

**Comment by bklin** [comment]
Czy mogę bezpiecznie wywalić suporty z sekcji o cores? Jakoś to przeoczyliśmy...

**Comment by szymtor** [comment]
Chyba tak. Nie wiem, po co one tam są. Nie wiem nawet, czy to ja tam je
wprowadziłem?

2015-01-18 10:56 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
Przeszedłem sekcję IVA. Problemy, które tam pozostały:

- w dowodzie Prop. 16 nie jest jasne skąd się bierze "polynomial time"; trzeba to jakimś dodatkowym zdaniem uzasadnić.

- nie czuję się na siłach przebrnąć przez dowód Prop. 20, zostawiam to lepszym.

Reszta powinna być OK.

**Comment by bklin** [comment]
Przeszedłem sekcję IV.B. Mam tylko jedną uwagę:

- w całej sekcji nie ma mowy o "equivariant templates". Może warto gdzieś na początku napisać że to nie przeoczenie, tylko faktycznie tak ma być, i że equvariant templates z atomami też pod tę sekcję podpadają.=

**Comment by bklin** [comment]
Przeszedłem sekcję IV.C i nie mam tam uwag.

**Comment by ochremiak** [comment]
Ja myślę, że czytelnik będzie już tak zafiksowany na ekwiwariantne rzeczy z
atomami, że nawet nie zauważy, że te wyniki są ogólniejsze ;) Ale ostatnie
zdanie pierwszego akapitu jest nieprawdziwe bez założenia o
definiowalności, więc je tam dodałam, co podkreśla, że mówimy między innymi
o rzeczach definiowalnych. Zobacz Bartek, czy tak jest Twoim zdaniem ok!

Wątpliwość: wyrzuciliśmy z tej sekcji przykład o strict width (jest
napisany, ale uznaliśmy, że to za dużo). A wstęp do sekcji IV B nadal mówi
o strict width (co jest oczywiście prawdą, że możemy to testować). Wywalić
to i zostawić tylko bounded width i few subpowers?

2015-01-18 11:54 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
On 18 Jan 2015, at 19:16, ochremiak wrote:

> Ja myślę, że czytelnik będzie już tak zafiksowany na ekwiwariantne rzeczy z 
> atomami, że nawet nie zauważy, że te wyniki są ogólniejsze ;)

Ja się bardziej martwiłem, że pomyśli że te wyniki są SZCZEgólniejsze, tzn. że
dotyczą tylko templatów bez atomów (inaczej: z trywialną akcją grupy). Ale:

> Ale ostatnie 
> zdanie pierwszego akapitu jest nieprawdziwe bez założenia o 
> definiowalności, więc je tam dodałam, co podkreśla, że mówimy między innymi 
> o rzeczach definiowalnych. Zobacz Bartek, czy tak jest Twoim zdaniem ok! 

To wygląda OK, i może nawet załatwia sprawę.

> Wątpliwość: wyrzuciliśmy z tej sekcji przykład o strict width (jest 
> napisany, ale uznaliśmy, że to za dużo). A wstęp do sekcji IV B nadal mówi 
> o strict width (co jest oczywiście prawdą, że możemy to testować). Wywalić 
> to i zostawić tylko bounded width i few subpowers? 

Tylko w tym miejscu to raczej nie powinno zostać. A może jednak nie wywalać? Miejsce 
mamy, a te dowody co w tej chwili wypadają do apendiksu to jakiś szczyt 
elegancji nie jest, mogą tam zostać moim zdaniem.

PS. Robię teraz jednocześnie nasz artykuł i slajdy o komputerze IBM 7090,
i przełączanie kontekstu za każdym razem robi mi zwarcie w mózgu, fajne uczucie :-)

**Comment by szymtor** [comment]
Generalnie jest niezła dupa w algebrze. 
Problem polega na tej redukcji wielomianowej.

Po pierwsze, potrzebujemy mieć prawdziwe skończone pp-definicje, a nie pp-definicje o skończonych 
dziedzinach i nieskończonej liczbie relacji. Ale to już załatwiłem w ostatnim commicie (niezbyt elegancko, dwa razy się pojawia coś a la zwartość).

Po drugie, potrzebujemy pokazać, że jeśli ppDef(B)⊆ppDef(C) to maszyna wielomianowa jest w stanie przekształcić instancję nad B w instancję nad C. Ona musi być w stanie przekształcić każdą
relację z B na pp-definicję w C, w sposób jednorodny. Pomysł, który teraz zapisuje jest brutalny i brudny.
Zakładam, że template B jest definiowalny. Wybieram reprezentantów orbit relacji templatu B,
niech to będą R_1,...,R_n. Dla każdego z nich jest skończona pp-formuła φ_i taka, że R_i=φ_i(C).

Teraz pokazujemy, jak przekształcić instancję I nad B w instancję nad C.
Dla każdego constrainta c=(x1,...,xk,R) w I, znajdujemy R_i takie, że R i R_i są w tej samej orbicie.
Bierzemy dowolne przekształcenie monotoniczne π które przekształca R_i w R, i aplikujemy je do formuły φ_i, dostając formułę φ_i'. Tę formułę wklejamy do I zamiast hiperkrawędzi (constrainta) c.
To jest wynikowa instancja I'.

To jest strasznie brzydkie. Mam nadzieję, że działa. Zapisuję.

**Comment by bklin** [comment]
Zapisuj. Na pierwszy rzut oka wygląda jakby działało, dowód idzie w apendix więc nie takie ważne że brzydki, a przed rebuttalem jeszcze to przemyślimy.

**Comment by szymtor** [comment]
Zrobione.
Teraz pojadę do domu, i stamtąd będę nadawał.

Sz.

2015-01-19 20:59 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
Dobra, to ja przejdę przez to co napisałeś.

**Comment by bklin** [comment]
Przeczytałem IVA(1)-(2). Dowód Prop. 23 wygląda wiarygodnie.

Zrobiłem takie zmiany (poza drobnymi poprawkami):

- przed Lemma 21 dodałem akapit wyjaśniający co ten lemat mówi.
- wyrzuciłem (wykomentowałem) listę rzeczy z początku sekcji IVA(1), bo była myląca, niezgodna ze strukturą twierdzeń i więcej przynosiła szkody niż pożytku.

Mam jedno pytanie:

Po co jest Lemma 21? 
- po pierwsze, chyba nigdzie nie jest jawnie używany
- jeżeli jest używany w jakimś dowodzie to po pierwsze trzeba jawnie się do niego odwołać
- a w głównym tekście gdzieś nadmienić "w dowodzie tego to a tego wyniku korzystamy z lematu 21"

Rozumiem że przez IVA(3) będziesz jeszcze szedł. A ja za Tobą :-)

**Comment by szymtor** [comment]
Lemat 21 jest kluczowy w Prop 24:

relacja niezmiennicza jest definiowana za pomocą uogólnionej pp-formuły.

2015-01-19 22:01 GMT+01:00 bklin <notifications@github.com>:

**Comment by szymtor** [comment]
Dodałem odniesnienia do tego lematu.

2015-01-19 22:29 GMT+01:00 szymon <szymtor@gmail.com>:
