### ISSUE TITLE
dowód lower bound

### ISSUE THREAD

**Issue by ochremiak** [szymtor/locfin#37]
Uwagi:
- "in other words, the symbols in the word w can be addressed by elements of B^n" - to brzmi tak, jakby to pod-zdanie zaczynające się od "in other words" podsumowywało wszystko co pada w tym zdaniu wcześniej. Ja na początku nie zrozumiałam o co chodzi, bo doszukiwałam się związku między tym stwierdzeniem a reprezentowaniem zmiennych przez ciągi długości p(n)...
- może zamiast "and accepts iff the instance I(w) includes the relation Ri(xb1; ... ; xbri )" napisać "includes the constraint ((xb1 ;... ; xbri ), Ri)"  ?
- "We can write the working of M using a QBF formula" - tak się pisze?
- konstrukcji na instancji nie umiem sprawdzić, ale wygląda dobrze :)

**Comment by bklin** [comment]
On 18 Jan 2015, at 13:12, ochremiak wrote:

> Uwagi:
> 
> 	• "in other words, the symbols in the word w can be addressed by elements of B^n" - to brzmi tak, jakby to pod-zdanie zaczynające się od "in other words" podsumowywało wszystko co pada w tym zdaniu wcześniej. Ja na początku nie zrozumiałam o co chodzi, bo doszukiwałam się związku między tym stwierdzeniem a reprezentowaniem zmiennych przez ciągi długości p(n)...

Zrobione

> 	• może zamiast "and accepts iff the instance I(w) includes the relation Ri(xb1; ... ; xbri )" napisać "includes the constraint ((xb1 ;... ; xbri ), Ri)" ?

Zrobione

> 	• "We can write the working of M using a QBF formula" - tak się pisze?

Nie wiem :-) Trochę zmieniłem, ale cały czas nie wiem. Z grubsza chyba jakoś tak się pisze.

> 	• konstrukcji na instancji nie umiem sprawdzić, ale wygląda dobrze :)

Witaj w klubie :-)

**Comment by eryxcc** [comment]
>> konstrukcji na instancji nie umiem sprawdzić, ale wygląda dobrze :)
> Witaj w klubie :-)
Ale czego dokładniej nie umiecie sprawdzić?

**Comment by bklin** [comment]
On 18 Jan 2015, at 23:04, eryxcc wrote:

> konstrukcji na instancji nie umiem sprawdzić, ale wygląda dobrze :)
> Witaj w klubie :-)
> Ale czego dokładniej nie umiecie sprawdzić?

No wiesz, tam trzeba trochę pomyśleć zeby się przekonać
że te warunki na końcu faktycznie są równoważne...

Ale spoko, da się to przeczytać.=
