### ISSUE TITLE
Jaki abstrakt?

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#38]
Uwagi do obecnego w nawiasach:

First-order definable structures with atoms are infinite,   [może napisać, że "we introduce fo structures"]
but they exhibit enough symmetry to be    [może symetrie – model-theoretic properties]
effectively manipulated. We study 
Constraint Satisfaction Problems (CSPs) over 
templates with atoms.                              [definable templates]
As an initial step, we consider locally      
finite templates, where every relation is finite.    [kluczowe info do zrozumienia: relacji może być ∞ wiele]
We argue that such templates occur naturally   [obecnie nasz nacisk zmienił się na badanie ∞ instancji]
in Descriptive Complexity Theory.

We study CSPs over such templates for 
both definable and finite instances.     [infinite, definable]
In the former case even decidability is not obvious, 
and to prove it we apply results from topological dynamics.
For finite instances, we show that some central results from 
the classical algebraic theory of CSPs still hold: 
the complexity is determined by polymorphisms 
of the template, and the existence of certain polymorphisms, 
such as majority or Maltsev polymorphisms, guarantees 
the correctness of classical algorithms
for solving finite CSP instances.

**Comment by bklin** [comment]
W pierwszym akapicie zostawiłbym symmetry zamiast model-theoretic properties.
W drugim akapicie nie rozumiem co chcesz zrobić. Może to po prostu zrób i zobaczymy?
W trzecim akapicie może "both finite and infinite, definable instances"? Tylko trzeba wtedy zmienić "former" na "latter".

**Comment by szymtor** [comment]
First-order definable structures with atoms
are infinite, but exhibit enough symmetry to be 
effectively manipulated. We study 
Constraint Satisfaction Problems (CSPs) 
where both the instance and the template
are definable structures with atoms.
As an initial step, we consider locally
finite templates, which contain potentially infinitely many finite relations. 
We argue that such templates occur naturally
in Descriptive Complexity Theory.

We study CSPs over such templates for 
both finite and infinite, definable instances.
In the latter case even decidability is not obvious, 
and to prove it we apply results from topological dynamics.
For finite instances, we show that some central results from 
the classical algebraic theory of CSPs still hold: 
the complexity is determined by polymorphisms 
of the template, and the existence of certain polymorphisms, 
such as majority or Maltsev polymorphisms, guarantees 
the correctness of classical algorithms
for solving finite CSP instances.

**Comment by bklin** [comment]
Mnie pasuje.

**Comment by ochremiak** [comment]
Mi tez.
18-01-2015 16:05, "bklin" <notifications@github.com> napisał(a):
