### ISSUE TITLE
Reprezentanty precz!

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#39]
Te prymitywy smrodzą w trzech miejscach, a w dwóch można się ich z korzyścią pozbyć.

* Lemat 9 (rozstrzygalność hom(I,T))
Tutaj, dowód może przeszukać wszystkie orbity I x T i sprawdzić, czy takie coś jest homomorfizmem.
To się sprowadza do napisania jakiejś formuły fo, więc rozstrzygalne.

* Proposition 11 (rozstrzygalność hom(I,T) lepiej)
Tutaj dowód się robi ładniejszy i krótszy, gdy zamiast reprezentantach orbit, mówić o orbitach.

* Theorem 25 (atlasy/squashing)
Tutaj, myślę, że nie tak łatwo się ich pozbyć.

**Comment by ochremiak** [comment]
Ja chyba nawet rozumiem i się zgadzam.

W Proposition 11 chcesz mieć orbity jako zmienne skończonej instancji oraz
constraint (o_1, ... o_n, R) in I^* whenever for some x_1, ... x_n such
that x_i \in o_i there is a constraint (x_1, ... , x_n, R) in I  ?
2015-01-18 15:34 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

**Comment by bklin** [comment]
Słuchajcie, ja Wam w tym nie pomogę. Nie mam czasu ani siły, a nie jest to moim zdaniem sprawa krytyczna. Sorry. 

Ale się nie sprzeciwiam, jeśli myślicie że tak będzie lepiej.

**Comment by szymtor** [comment]
Tak, to nie jest krytyczne. Jak będzie czas, to możemy zmienić.
Tym bardziej, że w Theorem 25 lemat o reprezentantach nie jest w ogóle
używany, bo te reprezentanty są konstruowane na miejscu.


2015-01-18 20:18 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
Żyjesz Szymek? Będziesz jutro? Bo może ktoś Cię zastąpi?

**Comment by szymtor** [comment]
Żyję, dzięki:)
Dam radę!

2015-01-18 20:24 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
Zamykam to, bo reprezentanty i tak wykwitły.
