### ISSUE TITLE
sekcja o LFP

### ISSUE THREAD

**Issue by bklin** [szymtor/locfin#40]
Przejrzałem sekcję o LFP. Bardzo fajna jest, nie ma się czego wstydzić!

Mam tylko jedno pytanie: czy tuż przed Lemma 31 można o templacie T_p zamiast "orbit-finite" powiedzieć "definable"?

**Comment by ochremiak** [comment]
Moim zdaniem możemy. Ale może na końcu trzeba dodać dla jasności
"... up to atom renaming, and each of them is definable." Albo coś w tym
stylu.

2015-01-18 16:30 GMT+01:00 bklin <notifications@github.com>:

**Comment by szymtor** [comment]
Walnąłem po prostu:

It is also not difficult to see that this structure is definable.

**Comment by bklin** [comment]
That's the spirit!
