### ISSUE TITLE
Które dowody do głównej części?

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#41]
Proponuję, oprócz tych które już są:

* Proposition 4 – o rozstrzyganiu =∈⊆ dla zbiorów definiowalnych. Może jedno zdanie ze szkicem? 
* Lemat 6 – o zwartości – też jedno zdanie ze szkicem
* Lemat 9 – o rozstrzyganiu hom(I,T) – jakby był jakiś ładny zwięzły dowód. Proponuję przeszukiwanie grafów funkcji (mogę spróbować napisać).
* Proposition 11 – z zastąpieniem reprezentantów orbitami
* Theorem 12 – napisać że to jest padding argument

P.S. Może warto dodać sformułowanie jakiegoś twierdzenia do drugiej połowy introduction, bo może się wydawać, że dowodzimy tylko tw. 1.

**Comment by bklin** [comment]
Myślę że to dobry pomysł, ale jak pożenić dodawanie szkiców z Twoim wspaniałym wynalazkiem o nazwie proofcol? Bo pełne dowody też powinny być, w apendiksie.

**Comment by szymtor** [comment]
Po prostu:

\begin{proof}[Proof (sketch):]
\end{proof}

proofcol zostawiamy. Ja mogę się spróbować zająć Lematem 9 i Proposition
11.

2015-01-18 20:53 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
On 18 Jan 2015, at 21:07, Szymon Toruńczyk wrote:

> Po prostu: 
> 
> \begin{proof}[Proof (sketch):] 
> \end{proof} 
> 
> proofcol zostawiamy. Ja mogę się spróbować zająć Lematem 9 i Proposition 
> 11. 

Tzn. zostawiamy żeby był czy zostawiamy żeby nie było?

**Comment by szymtor** [comment]
Żeby był. 
Proofcolami jeszcze się kiedyś zajmę, żeby lepiej wyglądały i w ogóle.

**Comment by bklin** [comment]
A, OK.

To ja się zajmę trzema pozostałymi, i może jeszcze jakimiś jak się rozpędzę.

Ale to gdzieś za godzinkę, najpierw skończę swoje slajdy na jutro.

**Comment by bklin** [comment]
Ja nie wiem czy jest sens się bawić z tymi szkicami dowodów, bo coraz krótszy ten artykuł się robi.

Related work trzeba napisać!

Ja w tej chwili grzebię w bibtexu, niedługo skończę i Wam przekażę, bo niektórych cytowań nie umiem uzupełnić.

**Comment by bklin** [comment]
Po namyśle głosuję za tym, żeby 
(1) nie robić szkiców dowodów i 
(2) zostawić \proofcol tak jak jest.
Uzasadnienie:
(1) każda zmiana to teraz okazja do pomyłki,
(2) to nie wygląda wcale tak źle. Artykułu nam przez to nie odwalą, a tak naprawdę ułatwi to recenzentom robotę.
