### ISSUE TITLE
Moje uwagi

### ISSUE THREAD

**Issue by eryxcc** [szymtor/locfin#42]
Moje uwagi:

- komentarze po sformułowaniu Twierdzenia 1: trzeba napisać, że "our technical tool" dotyczy rozstrzygalności/upper boundu, podobnie Tw Ramseya dowodzi rozstrzygalności/upper boundu

- ", sometimes arise naturally" - chyba bez przecinka

- Lemat 5 o reprezentantach (a także Lematy 3 i 4) nie podają złożoności, a jest ona
  konieczna, by udowodnić Proposition 11 (o redukcji PSPACE).

- w sformułowaniu Tw 1 i 11 ja bym dopisał "poly" do redukcji z założenia, bo tak jest ciekawiej

**Comment by szymtor** [comment]
Dzięki Eryk!

Super, że to czytasz. Przeczytasz całe?

2015-01-18 21:41 GMT+01:00 eryxcc <notifications@github.com>:

**Comment by eryxcc** [comment]
Zobaczę :)

**Comment by szymtor** [comment]
A mógłbyś poprawić te złożoności w lematach 3,4,5?

Bo ja chyba już nie jestem w stanie myśleć – chyba mam gorączkę,
i odpuszczę sobie dziś.

Sz.

**Comment by eryxcc** [comment]
Część rzeczy jest numerowane tak jak dowody, a część nie. Teraz mamy: Ex 1, Ex 2, Thm 1, Thm 2, Ex 3, Ex 4, Ex 5, Ex 6, Thm 3, Prop 4, Lemma 5, Ex 7, ... Jest w tym jakaś głębsza myśl? Chyba wszystko powinno być numerowane razem, bo tak trudno coś znaleźć.

**Comment by szymtor** [comment]
Tak, możesz naprawić? Może w każdej sekcji odnowa numeracja?

**Comment by bklin** [comment]
E tam, co my książkę piszemy? Normalnie niech leci jednym ciągiem.

**Comment by ochremiak** [comment]
Tak, tak! Jednym ciągiem!

2015-01-18 22:48 GMT+01:00 bklin <notifications@github.com>:

>
> E tam, co my książkę piszemy? Normalnie niech leci jednym ciągiem.
>
> On 18 Jan 2015, at 22:47, Szymon Toruńczyk wrote:
>
> > Tak, możesz naprawić? Może w każdej sekcji odnowa numeracja?

**Comment by eryxcc** [comment]
> A mógłbyś poprawić te złożoności w lematach 3,4,5?

OK, dopisałem wszędzie PSPACE, mam nadzieję, że poprawnie (wygląda ok).

**Comment by eryxcc** [comment]
Jeden ciąg też zrobiłem.
