### ISSUE TITLE
Translated in polynomial space

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#43]
Czy jak piszemy:

Fact 42. Every first order formula φ can be translated in polynomial space into a quantifier-free formula φ′, such that φ and φ′ are equivalent in the structure (A, =).

to czy to nie sugeruje, że formuła φ' jest rozmiaru wielomianowego? Podobnie, przy innych miejscach, gdy myślimy o redukcjach pspacowych, ale piszemy "can be translated in polynomial space".

**Comment by bklin** [comment]
Moim zdaniem to jest OK, ale jeśli wolisz, to nic nas nie kosztuje dopisać "formula (of possibly exponential size", albo "(possibly exponentially long) formula". Zróbmy tak wobec tego.
