### ISSUE TITLE
strict bounded width w sekcji IV B

### ISSUE THREAD

**Issue by ochremiak** [szymtor/locfin#44]
Dorzucamy ten przykład, czy wyrzucamy wzpomnienie o strict bounded width z "wprowadzenia" do tej sekcji?

**Comment by szymtor** [comment]
Jak uważasz. Ja teraz się skupiam na doprowadzeniu Algebry do porządku.

2015-01-19 18:29 GMT+01:00 ochremiak <notifications@github.com>:

**Comment by bklin** [comment]
Usunąłem strict bounded width
