### ISSUE TITLE
Nowe dowody

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#45]
Napisałem kilka nowych dowodów, które są podatne na błędy. Ostatni z nich pojawia się w tekście głównym. Może powinien być oznaczony jako "sketch". Sprawdźcie, proszę.

1) Zmieniłem dowód Lematu 21, żeby robił prawdziwie skończone instancje. Przy okazji, zmieniłem definicje, tak, żeby mówić o pp-formułach (prawdziwe, skończone formuły, fragment FO), i o "generalized pp-formulas). 
2) Uzupełniłem sporą lukę w Proposition 23, o redukcji wielomianowej.
3) Przywróciłem i udowodniłem charakteryzację rdzeni jako lokalnych rdzeni w Proposition 27.
4) To po to, by napisać jak idzie dowód Corollary 31.

**Comment by szymtor** [comment]
Idę spać. Jutro spróbuję rano wstać i przeczytać cały artykuł.
Jakby były jakieś pilne sprawy, to dzwońcie.

Sz.

**Comment by ochremiak** [comment]
Hej!

Przeczytałam cały artykuł (poza dowodami 24 o ppdef=InvPol i 27 o
rdzeniach) i mi się podoba :)

Szymon, jesteś mega dzielny!


2015-01-20 1:39 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

> Napisałem kilka nowych dowodów, które są podatne na błędy. Ostatni z nich
> pojawia się w tekście głównym. Może powinien być oznaczony jako "sketch".
> Sprawdźcie, proszę.
>
> 1) Zmieniłem dowód Lematu 21, żeby robił prawdziwie skończone instancje.
> Przy okazji, zmieniłem definicje, tak, żeby mówić o pp-formułach
> (prawdziwe, skończone formuły, fragment FO), i o "generalized pp-formulas).
>
Przeczytałam i wydaje mi się, że wszystko jest ok.


>
> 2) Uzupełniłem sporą lukę w Proposition 23, o redukcji wielomianowej.
>
Jak wyżej.

> 3) Przywróciłem i udowodniłem charakteryzację rdzeni jako lokalnych rdzeni
> w Proposition 27.
>
Na to nie starczyło mi siły...

> 4) To po to, by napisać jak idzie dowód Corollary 31.
>
Skąd wynika, że T|_A ma bounded width? Bo to ma dodatkowe relacje, a po
drugie nie jest podtemplatem tylko indukowaną podstrukturą. Ale może to
trywialne tylko jest późno...
