### ISSUE TITLE
Dwie wątpliwości

### ISSUE THREAD

**Issue by ochremiak** [szymtor/locfin#46]
1) Dowód Corollary 31 - skąd wiadomo, że T|_A ma bounded width?

2) Konstrukcja instancji F_E(T) dla rozstrzygania E-polimorfizmów w Twierdzeniu 29 - Chyba nigdzie w artykule nie jest w tej chwili napisane co to jest produkt templatów jako struktura relacyjna/instancja. Kiedyś polimorfizmy były w ten sposób definiowane, ale to zniknęło.

**Comment by szymtor** [comment]
Sekcja 3 nazywa się orbit finite instances. Zmieniamy na definable?

**Comment by ochremiak** [comment]
Albo Infinite.


2015-01-20 8:37 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:

> Sekcja 3 nazywa się orbit finite instances. Zmieniamy na definable?

**Comment by szymtor** [comment]
Po co w dowodzie lematu 34 jest zdanie
"that (F_E(T)) instance is definable if T is"?
Chyba ani nie zakładamy, że T jest definiowalne, ani nie potrzebujemy, żeby
F_E(T) było. Co więcej, nie musi być, jeżeli E używa nieskończenie wielu
symboli funkcyjnych.

2015-01-20 8:48 GMT+01:00 ochremiak <notifications@github.com>:

> Albo Infinite.
>
>
> 2015-01-20 8:37 GMT+01:00 Szymon Toruńczyk <notifications@github.com>:
>
> > Sekcja 3 nazywa się orbit finite instances. Zmieniamy na definable?

**Comment by ochremiak** [comment]
A nie po to zeby rozstrzygac istnienie E-polimorfizmow dla definiowalnych
templatow?
20-01-2015 09:59, "Szymon Toruńczyk" <notifications@github.com> napisał(a):

**Comment by szymtor** [comment]
My tu nie pokazujemy nic na temat rozstrzygalności.

2015-01-20 10:08 GMT+01:00 ochremiak <notifications@github.com>:

**Comment by ochremiak** [comment]
A gdzies mowimy? Tzn. mowimy w komentarzach. Ale czy gdzies formalnie
piszemy czemu dla definiowalnego T istnienie e-poli jest rozstrzygalne
(przy skonczonym E)?
20-01-2015 10:09, "Szymon Toruńczyk" <notifications@github.com> napisał(a):

**Comment by szymtor** [comment]
Chyba nie.

2015-01-20 10:14 GMT+01:00 ochremiak <notifications@github.com>:

**Comment by ochremiak** [comment]
No to moze dopisz w tym miejscu ze dla skonczonych E ta inst jest
definiowalna i hopefully czytelnik sie polapie ze o to nam chodzi gdy
mowimy o rozstrzygalnosci istnienia e-poli
20-01-2015 10:14, "Szymon Toruńczyk" <notifications@github.com> napisał(a):

**Comment by szymtor** [comment]
OK, ale ja i tak nie widzę po co w dowodzie lem 34 nam ta definiowalność.

2015-01-20 10:19 GMT+01:00 ochremiak <notifications@github.com>:

**Comment by ochremiak** [comment]
Submit!!
20-01-2015 10:20, "Szymon Toruńczyk" <notifications@github.com> napisał(a):

**Comment by szymtor** [comment]
* Umieściłem definicję struktury relacyjnej T^k. 

* Moim zdaniem, T|_A ma bounded width, bo jest pod-templatem T (w przypadku, gdy T jest corem).
To wynika z dowodu Proposition 27, pewnie powinno być dodane do warunku 3): and is a subtemplate of 
(T,ppDef(T)).
