### ISSUE TITLE
zlecenia do prelim

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#7]
Zbieram zamówienia na pojęcia objaśnione w prelim.

Wstępna lista:
* zbiory z atomami, orbitowa skończoność, przykłady, skończona prezentacja, 
* CSP, w wariancie instancja = zmienne+constrainty
* CSP, w wariancie homomorficznym
* orbitowo-skończone sygnatury, templaty itd.
* Działania grup? To może lepiej na miejscu zdefiniować.

Co jeszcze?

**Comment by ochremiak** [comment]
Ja mam póki co spisane takie rzeczy:

- finite template (skończony nośnik i skończenie wiele relacji?)  (chyba,
że to jest potrzebne tylko mi przy charakteryzacji korzystających z wyników
dla finite CSP)

- Założenie, że w strukturach nie ma isolated nodes? Ja bym była za tym,
żeby to napisać bardzo wyraźnie w preliminaries i potem już nie powtarzać
na każdym kroku.

- partial solution (dodać to przy definicji CSP)



2015-01-05 21:45 GMT+01:00 bklin <notifications@github.com>:

**Comment by szymtor** [comment]
Orbit-finite czy orbit finite?
Locally-finite czy locally finite?

**Comment by ochremiak** [comment]
Orbit-finite

Locally finite
06-01-2015 14:16, "Szymon Toruńczyk" <notifications@github.com> napisał(a):

**Comment by ochremiak** [comment]
Uwagi do prelim:

- Zlecenie: Polimorfizmy.

Piszemy o nich w intro, pojawią się przy konstrukcji templatu skończonego i
przy charakteryzacji złożoności. No i oczywiście przy teorii alg.

- W intro pokazujemy, że 3-colorability redukuje się do CSP. Może argument,
że CSP jest NP-complete może odwołać się do tego, a nie wprowadzać 3-SAT?

- Złożoność CSP (a dokładniej całe podpunkty d) i e)  ) . W intro mówimy
dużo o nieskończonych instancjach (na końcu podpunktuc) też). Trzeba więc
tu bardzo jasno napisać, że przytaczane wyniki dotyczące złożoności CSP(T)
dotyczą skończonych instancji. "An instance is encoded by listing..." to
też dotyczy tylko instancji skończonych...

Teraz będę czytać atomy...

**Comment by ochremiak** [comment]
Zbiór tupli jest najpierw oznaczany przez A^{[n]} (w nawiasach
kwadratowych), a potem (a właściwie zazwyczaj) przez A^n.

2015-01-06 21:35 GMT+01:00 Joanna Ochremiak <joanna.ochremiak@gmail.com>:

**Comment by bklin** [comment]
note to self: dodać polimorfizmy i E-polimorfizmy do prelimsów.
